<a href="https://colab.research.google.com/github/mariliaoliv/Fundamentos-de-Programa-o/blob/main/Aula05.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
np_2d = np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, 68.7]])
print(np_2d)

[[ 1.73  1.68  1.71  1.89  1.79]
 [65.4  59.2  63.6  88.4  68.7 ]]


In [ ]:
# mostra a quatidade de linhas e colunas
print(np_2d.shape)

(2, 5)


In [ ]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
                  [65.4, 59.2, 63.6, 88.4, "68.7"]])

array([['1.73', '1.68', '1.71', '1.89', '1.79'],
       ['65.4', '59.2', '63.6', '88.4', '68.7']], dtype='<U32')

In [ ]:
np.array([[1.73, 1.68, 1.71, 1.89, 1.79],
         [65.4, 59.2, 63.6, 88.4, 68.7],
          [2.4, 45.6, 67.8, 12.4, 55.5]])


array([[ 1.73,  1.68,  1.71,  1.89,  1.79],
       [65.4 , 59.2 , 63.6 , 88.4 , 68.7 ],
       [ 2.4 , 45.6 , 67.8 , 12.4 , 55.5 ]])

In [ ]:
np_2d[0]

array([1.73, 1.68, 1.71, 1.89, 1.79])

In [ ]:
np_2d[0][2] #lista zero coluna dois

1.71

In [ ]:
np_2d[:, 1:3]

array([[ 1.68,  1.71],
       [59.2 , 63.6 ]])

In [ ]:
np_2d[1, :]

array([65.4, 59.2, 63.6, 88.4, 68.7])

In [ ]:
baseball = [180, 215, 210, 188, 176, 209, 200]
# importe a biblioteca numpy com acesso via np
import numpy as np
# use np.array() para converter a lista baseball para um array 
np_baseball = np.array( [180, 215, 210, 188, 176, 209, 200])
# print o tipo da estrutura de dados np_baseball
print(type(np_baseball))
#print as dimensões do array np_baseball
print(np_baseball.shape) # as dimensões são as linhas e as colunas. para exibilas basta colocar shape ao final ex: list.shape

<class 'numpy.ndarray'>
(7,)


In [4]:
import random as rd
import numpy as np
# geraçao de numeros entre 150 e 209
height = range(150, 210)
# geraçao de numeros entre 50 e 149 
weight = range(50, 150)
# amostra randomimca de 20 numeros de height
height = rd.sample(height, 20)
print(height)
# amostra randomica de 20 numeros de weight 
weight = rd.sample(weight,20)
print(weight)
 
# converter height em array e normalizar multiplicando po 0.01 
height_array = np.array(height)
height_array = height_array*0.01

#converter weight em array
weight_array = np.array(weight)

# calculo bmi 
bmi = weight_array/height_array**2
print(bmi)
# verificaçao de onde bmi é menor que 21 
light = bmi<21
print(light)
# exibiçao dos valores de bmi om valor menor que 21 
print(bmi[bmi<21])
# print os elementos de weight_array do index 8 até o index 15 
print(weight_array[7:16])
# print os elementos de height_array do index 8 até o index 15
print(height_array[7:16])
# print os elementos de height_array de index 15 até o index 19 
print(height_array[14:20])

[199, 202, 193, 166, 159, 179, 188, 154, 208, 158, 171, 190, 205, 207, 176, 170, 161, 178, 200, 203]
[123, 115, 131, 58, 134, 60, 104, 126, 85, 53, 119, 88, 91, 96, 143, 100, 55, 136, 57, 101]
[31.05982172 28.18351142 35.16872936 21.04804761 53.00423243 18.7260073
 29.42507922 53.12868949 19.64681953 21.23057202 40.69628262 24.3767313
 21.65377751 22.40425681 46.16477273 34.60207612 21.21831719 42.92387325
 14.25       24.50920915]
[False False False False False  True False False  True False False False
 False False False False False False  True False]
[18.7260073  19.64681953 14.25      ]
[126  85  53 119  88  91  96 143 100]
[1.54 2.08 1.58 1.71 1.9  2.05 2.07 1.76 1.7 ]
[1.76 1.7  1.61 1.78 2.   2.03]


In [8]:
baseball = [[180, 78.4],[215, 182.7],[210, 98.5],[188, 75.2]]
import numpy as np 
np_baseball = np.array(baseball)
#print a terceira linha de np_baseball na linha 14
print(np_baseball[2:])
#crie uma nova variavel np_weight_lb que receba toda a segunda coluna de np_baseball
np_weight_bl = np_baseball[:, 1]
#Print a primeira coluna da segunda linha de Np_baseball na linha  do código.
print(np_baseball[1, 0])
#Calcule e exiba a média da primeira coluna de np_baseball.
print(np.mean(np_baseball[0])) #list.mean exibe a média dos valores contidos na lista 
#Calcule e exiba a mediana da segunda linha de np_baseball.
print(np.median(np_baseball[1]))

[[210.   98.5]
 [188.   75.2]]
215.0
129.2
198.85


Os arrays tem por finalidade armazenar vários dados do mesmo tipo juntos como se tivéssemos vários elementos dentro de uma única variável.

O NumPy é uma biblioteca para a linguagem Python com funções para se trabalhar com computação numérica. Seu principal objeto é o vetor n-dimensional, ou ndarray . Um vetor n-dimensional também é conhecido pelo nome tensor.

In [ ]:
np_2d[0, 2]

1.71